{{- if .Values.blueGreen.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fuse.fullname" . }}-preview
  labels: {{- include "fuse.labels" . | nindent 4 }}
    app.kubernetes.io/component: preview
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fuse.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/slot: {{ .Values.blueGreen.activeSlot | default "blue" | eq "blue" | ternary "green" "blue" }}
{{- end }}
