{{- if .Values.metrics.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "fuse.fullname" . }}
  labels: {{- include "fuse.labels" . | nindent 4 }}
    {{- with .Values.metrics.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.serviceMonitor.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels: {{- include "fuse.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: {{ .Values.metrics.serviceMonitor.path | default "/metrics" }}
      interval: {{ .Values.metrics.serviceMonitor.interval | default "30s" }}
      scrapeTimeout: {{ .Values.metrics.serviceMonitor.scrapeTimeout | default "10s" }}
      honorLabels: {{ .Values.metrics.serviceMonitor.honorLabels | default false }}
      {{- with .Values.metrics.serviceMonitor.relabelings }}
      relabelings: {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.metrics.serviceMonitor.metricRelabelings }}
      metricRelabelings: {{- toYaml . | nindent 8 }}
      {{- end }}
  namespaceSelector:
    {{- if .Values.metrics.serviceMonitor.namespaceSelector }}
    {{- toYaml .Values.metrics.serviceMonitor.namespaceSelector | nindent 4 }}
    {{- else }}
    matchNames:
      - {{ .Release.Namespace }}
    {{- end }}
  {{- with .Values.metrics.serviceMonitor.targetLabels }}
  targetLabels: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.metrics.serviceMonitor.podTargetLabels }}
  podTargetLabels: {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.metrics.serviceMonitor.sampleLimit }}
  sampleLimit: {{ . }}
  {{- end }}
{{- end }}
